# script to monitor specific OSM elements modified during last 24h
# query: http://overpass-turbo.eu/s/Fr0

# if changesets!=0, telegram message to $CANALE will be sent with links to achavi
# REQUIRES telegram-cli installed and telegram channel $CANALE created

# adding the following row to crontab will check daily at 00:05 AM:
# 5 0 * * * <path>/monitor_CAI.sh >> /dev/null 2>&1


######## start customization
REGIONE="TTA"
CANALE=CAI$REGIONE
TELEGRAMCLIPATH=/home/pi/apps/tg/bin/
######## end customization

T0=`date -d "yesterday 00:00" '+%Y-%m-%d'`T00:00:00Z
T1=`date +"%Y-%m-%d"`T00:00:00Z
IERI=`date -d "yesterday 00:00" '+%Y-%m-%d'`
OGGI=`date +"%Y-%m-%d"`
MESSAGGIO="Ci sono modifiche alla rete sentieri $REGIONE tra $IERI e $OGGI"
NOMODS="Non ci sono modifiche tra $T0 e $T1"
REGIONEQ=$REGIONE'adiff'$OGGI'.xml'


RUN=`date`

# link generated by export compact query http://overpass-turbo.eu/s/Fr0
# please, customize above query, then copy exported compact query link
# replace below variable value with such link 
QUERYGEO="http://overpass-api.de/api/interpreter?data=%5Bout%3Axml%5D%5Btimeout%3A300%5D%5Badiff%3A%22$T0%3A00%3A00Z%22%2C%22$T1%3A00%3A00Z%22%5D%3Barea%283600042611%29%2D%3E%2EsearchArea%3B%28relation%5B%22operator%22%3D%22Club%20Alpino%20Italiano%22%5D%28area%2EsearchArea%29%3Brelation%5B%22operator%22%3D%22CAI%22%5D%28area%2EsearchArea%29%3B%29%3B%28%2E%5F%3B%3E%3B%29%3Bout%20meta%20geom%3B%0A"

cd /tmp
rm $REGIONE*

echo "extracting yesterday differences ..."
wget -O $REGIONEQ "$QUERYGEO"

echo "parsing involved changeset(s)"
cat $REGIONEQ | grep "$IERI\|$OGGI" | grep changeset | awk ' { print substr($0,index($0, "changeset")+11,8) }' > $REGIONEchangeset.lst

echo "sorting and compacting changeset list"
sort -u $REGIONEchangeset.lst -o $REGIONEchangeset.lst

echo "counting changesets involved"
CHAN=`cat $REGIONEchangeset.lst | wc -l`

echo "writing talegram message header"
echo "Ci sono modifiche alla rete sentieri $REGIONE tra $T0 e $T1" >  $REGIONEtelegram_msg.txt

echo "building changeset list in telegram message"
while read -r line
do
    name="$line"
    echo "https://overpass-api.de/achavi/?changeset=$name" >> $REGIONEtelegram_msg.txt
done < "$REGIONEchangeset.lst"

if [ $CHAN == 0 ]
then 
   (sleep 6; echo "msg $CANALE $NOMODS"; echo "safe_quit") | $TELEGRAMCLIPATH/telegram-cli -W
#  echo "non ci sono modifiche tra $IERI e $OGGI"
   else
   (sleep 6; echo "send_text $CANALE $REGIONEtelegram_msg.txt"; echo "safe_quit") | $TELEGRAMCLIPATH/telegram-cli -W
fi
