#!/bin/bash

# script to monitor specific OSM elements modified during the day
# query:
# http://overpass-turbo.eu/s/Fr0

# if changesets!=0, telegram message to CANALE will be sent with links to achavi

T0=`date -d "yesterday 00:00" '+%Y-%m-%d'`T00:00:00Z
T1=`date +"%Y-%m-%d"`T00:00:00Z

IERI=`date -d "yesterday 00:00" '+%Y-%m-%d'`
OGGI=`date +"%Y-%m-%d"`

REGIONE="Emilia Romagna"
CANALE=CAIER
MESSAGGIO="Ci sono modifiche alla rete sentieri tra $IERI e $OGGI"

RUN=`date`

# link generated by export compact query http://overpass-turbo.eu/s/Fr0
# please, customize above query, then copy exported compact query link
# replace below variable value with such link 
QUERYGEO="http://overpass-api.de/api/interpreter?data=%5Bout%3Axml%5D%5Btimeout%3A300%5D%5Badiff%3A%22$T0%3A00%3A00Z%22%2C%22$T1%3A00%3A00Z%22%5D%3Barea%283600042611%29%2D%3E%2EsearchArea%3B%28relation%5B%22operator%22%3D%22Club%20Alpino%20Italiano%22%5D%28area%2EsearchArea%29%3Brelation%5B%22operator%22%3D%22CAI%22%5D%28area%2EsearchArea%29%3B%29%3B%28%2E%5F%3B%3E%3B%29%3Bout%20meta%20geom%3B%0A"

cd /tmp
rm CAIER*

echo "extracting CAIER yesterday differences ..."
wget -O CAIERadiff$OGGI.xml "$QUERYGEO"

echo "parsing changesets involved"
cat CAIERadiff$OGGI.xml | grep "$IERI\|$OGGI" | grep changeset | awk ' { print substr($0,index($0, "changeset")+11,8) }' > CAIERchangeset.lst

echo "sorting and compacting changeset list"
sort -u CAIERchangeset.lst -o CAIERchangeset.lst

echo "counting changesets involved"
CHAN=`cat CAIERchangeset.lst | wc -l`

echo "writing talegram message header"
echo "Ci sono modifiche alla rete sentieri $REGIONE tra $T0 e $T1" >  CAIERtelegram_msg.txt

echo "building changeset list in telegram message"
while read -r line
do
    name="$line"
    echo "https://overpass-api.de/achavi/?changeset=$name" >> CAIERtelegram_msg.txt
done < "CAIERchangeset.lst"

if [ $CHAN == 0 ]
then 
   echo "No changes in $REGIONE between $T0 and $T1"
else
   (sleep 6; echo "send_text $CANALE CAIERtelegram_msg.txt"; echo "safe_quit") | /home/pi/apps/tg/bin/telegram-cli -W
fi

