#!/bin/bash

if [ $# -eq 0 ]
   then
     echo "first argument how many days ago monitor changes"
     echo "second argument area name"
     echo "...exiting"
     exit
fi

if [ -z "$2" ]
  then
    echo "No area supplied"
    exit
fi    
PLACE=$2" "$3" "$4" "$5
PLACE=${PLACE// /%20}



T0=`date -d "yesterday 00:00" '+%Y-%m-%d'`T00:00:00Z
T1=`date +"%Y-%m-%d"`T00:00:00Z
IERI=`date -d "yesterday 00:00" '+%Y-%m-%d'`
OGGI=`date +"%Y-%m-%d"`
if [[ "$1" =~ ^[0-9]+$ ]] ; then 
   T0=`date -d "$1 days ago 00:00" '+%Y-%m-%d'`T00:00:00Z
   IERI=`date -d "$1 days ago 00:00" '+%Y-%m-%d'`
fi
echo $PLACE
echo $T0
echo $T1
echo $IERI
echo $OGGI
